MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  FCOS_ON: True
  SOFT_NMS: False 
  FCOS:
    NUM_CLASSES: 3
    NMS_TH: 0.5
    REG_LOSS_TYPE: "BIOU"
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
DATASETS:
  TEST: ("woods_test",)
  IMG_DIRS_TRAIN: ("/home/hancock/data/woods_new","/home/hancock/data/woods_new")
  ANNOTS_TRAIN: ("/home/hancock/data/woods/annots/train.json", "/home/hancock/data/woods/annots/val.json")
  IMG_DIRS_VAL: ("/home/hancock/data/woods_new",)
  ANNOTS_VAL: ("/home/hancock/data/woods/annots/test.json",)
  IMG_DIRS_TEST: ("/home/hancock/data/woods_new",)
  ANNOTS_TEST: ("/home/hancock/data/woods/annots/test.json",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  LR_SCHEDULER: "CosineAnealing"
  WARMUP_ITERS: 1000 
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  ETA_MIN: 0.0
  MAX_ITER: 60000 
  IMS_PER_BATCH: 4 
  WARMUP_METHOD: "linear"
VAL:
  PERIOD: 5000
OUTPUT_DIR: "/home/hancock/data/training_records/fcos/woods/FCOS_R50_GIOU_60K"
