MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
DATASETS:
  TEST: ("voc2007_test",)
  IMG_DIRS_TRAIN: ("/home/hancock/training_data/VOC/VOCdevkit/VOC2007/JPEGImages","/home/hancock/training_data/VOC/VOCdevkit/VOC2007/JPEGImages")
  ANNOTS_TRAIN: ("/home/hancock/training_data/VOC/PASCAL_VOC/pascal_train2007.json", "/home/hancock/training_data/VOC/PASCAL_VOC/pascal_val2007.json")
  IMG_DIRS_VAL: ("/home/hancock/training_data/VOC/VOCdevkit/VOC2007/JPEGImages",)
  ANNOTS_VAL: ("/home/hancock/training_data/VOC/PASCAL_VOC/pascal_test2007.json",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 8 
SOLVER:
  LR_SCHEDULER: "CosineAnealing"
  WARMUP_ITERS: 2000 
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  ETA_MIN: 0.00001
  MAX_ITER: 150000
  IMS_PER_BATCH: 4 
  WARMUP_METHOD: "linear"
VAL:
  PERIOD: 5000
OUTPUT_DIR: "/home/hancock/data/training_records/fcos/VOC/FCOS_R50_0.0025"