MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
DATASETS:
  TEST: ("voc2007_test",)
  IMG_DIRS_TRAIN: ("/home/hancock/training_data/VOC/VOCdevkit/VOC2007/JPEGImages","/home/hancock/training_data/VOC/VOCdevkit/VOC2007/JPEGImages")
  ANNOTS_TRAIN: ("/home/hancock/training_data/VOC/PASCAL_VOC/pascal_train2007.json", "/home/hancock/training_data/VOC/PASCAL_VOC/pascal_val2007.json")
  IMG_DIRS_TEST: ("/home/hancock/training_data/VOC/VOCdevkit/VOC2007/JPEGImages",)
  ANNOTS_TEST: ("/home/hancock/training_data/VOC/PASCAL_VOC/pascal_test2007.json",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (100, 200)
  MAX_ITER: 300
  IMS_PER_BATCH: 4 
  WARMUP_METHOD: "constant"
OUTPUT_DIR: "/tmp/dataload_test"